"""200 Comprehensive Sales Prompts — Niche, Positioning, Competition, Strengths, Weaknesses"""

COMPREHENSIVE_PROMPTS = {
    # NICHE DEFINITION (20 prompts)
    "niche_001": {"title": "Narrow vs Broad Market", "focus": "Define optimal market scope", "tactics": ["beachhead strategy", "TAM analysis", "early adopter targeting"]},
    "niche_002": {"title": "Customer Persona Deep Dive", "focus": "Build detailed buyer profile", "tactics": ["demographics", "psychographics", "buying behavior", "pain points"]},
    "niche_003": {"title": "Underserved Market Detection", "focus": "Find gaps competitors miss", "tactics": ["competitor mapping", "customer interviews", "market research"]},
    "niche_004": {"title": "Niche Validation Framework", "focus": "Verify niche viability", "tactics": ["size check", "willingness to pay", "accessibility test"]},
    "niche_005": {"title": "Vertical vs Horizontal Play", "focus": "Choose market direction", "tactics": ["vertical advantages", "horizontal scaling", "hybrid approach"]},
    "niche_006": {"title": "Customer Job to be Done", "focus": "Understand core need", "tactics": ["outcome-driven marketing", "emotional driver identification"]},
    "niche_007": {"title": "Niche Expansion Path", "focus": "Plan growth trajectory", "tactics": ["adjacent markets", "cross-sell opportunities", "market sequence"]},
    "niche_008": {"title": "Competitive Niche Selection", "focus": "Choose defensible position", "tactics": ["moat analysis", "differentiation", "switching costs"]},
    "niche_009": {"title": "Geographic Niche Strategy", "focus": "Identify regional opportunities", "tactics": ["local market analysis", "regional preferences", "expansion path"]},
    "niche_010": {"title": "B2B vs B2C Niche", "focus": "Segment business type", "tactics": ["buyer behavior differences", "decision cycle length", "contract value"]},
    "niche_011": {"title": "Premium vs Mass Market Niche", "focus": "Choose price positioning", "tactics": ["quality perception", "willingness to pay", "margin targets"]},
    "niche_012": {"title": "Solution vs Problem Niche", "focus": "Lead with need or answer", "tactics": ["problem awareness", "solution education", "adoption barriers"]},
    "niche_013": {"title": "Emerging Trend Niche", "focus": "Ride new market waves", "tactics": ["trend identification", "early adoption positioning", "thought leadership"]},
    "niche_014": {"title": "Seasonal Niche Dynamics", "focus": "Leverage time-based demand", "tactics": ["peak season strategy", "off-season retention", "inventory planning"]},
    "niche_015": {"title": "Pain-Based Niche", "focus": "Target urgent problems", "tactics": ["pain severity assessment", "time-to-value optimization", "emergency positioning"]},
    "niche_016": {"title": "Desire-Based Niche", "focus": "Appeal to aspirations", "tactics": ["lifestyle marketing", "status signaling", "emotional connection"]},
    "niche_017": {"title": "Efficiency Niche", "focus": "Cost/time savings focus", "tactics": ["ROI calculation", "productivity metrics", "efficiency benchmarks"]},
    "niche_018": {"title": "Transformation Niche", "focus": "Before/after positioning", "tactics": ["success stories", "transformation timeline", "proof points"]},
    "niche_019": {"title": "Community-Driven Niche", "focus": "Build tribe around identity", "tactics": ["belonging factor", "shared values", "community engagement"]},
    "niche_020": {"title": "Niche Sustainability Check", "focus": "Long-term viability", "tactics": ["market size over time", "trend trajectory", "profitability threshold"]},

    # MARKET POSITIONING (25 prompts)
    "positioning_001": {"title": "Value Proposition Clarity", "focus": "Crystal clear benefit statement", "tactics": ["benefit hierarchy", "unique claims", "proof points"]},
    "positioning_002": {"title": "Differentiation Audit", "focus": "Identify true advantages", "tactics": ["feature comparison", "benefit differentiation", "cost advantage"]},
    "positioning_003": {"title": "Messaging Architecture", "focus": "Layered communication strategy", "tactics": ["headline", "subheading", "supporting claims", "proof"]},
    "positioning_004": {"title": "Brand Personality", "focus": "Define voice and tone", "tactics": ["archetypes", "personality traits", "communication style"]},
    "positioning_005": {"title": "Category Position", "focus": "Market category leadership", "tactics": ["category definition", "category leadership", "alternatives comparison"]},
    "positioning_006": {"title": "Price Positioning", "focus": "Strategic price perception", "tactics": ["premium positioning", "value justification", "price anchoring"]},
    "positioning_007": {"title": "Competitor Positioning", "focus": "Map vs alternatives", "tactics": ["competitive matrix", "advantage claims", "comparison strategy"]},
    "positioning_008": {"title": "Emotional Positioning", "focus": "Tap into feelings", "tactics": ["emotional triggers", "aspirational messaging", "fear/desire balance"]},
    "positioning_009": {"title": "Rational Positioning", "focus": "Data-driven approach", "tactics": ["ROI emphasis", "feature benefits", "specification advantages"]},
    "positioning_010": {"title": "Hybrid Positioning", "focus": "Combine emotional + rational", "tactics": ["feel + benefit", "heart + head", "story + data"]},
    "positioning_011": {"title": "First-Mover Positioning", "focus": "Pioneer advantage claim", "tactics": ["innovation narrative", "market education", "standard-setting"]},
    "positioning_012": {"title": "Fast-Follower Positioning", "focus": "Improved alternative", "tactics": ["better execution", "lessons learned", "trust building"]},
    "positioning_013": {"title": "Niche-Specialist Positioning", "focus": "Depth over breadth", "tactics": ["specialization claim", "deep expertise", "niche dominance"]},
    "positioning_014": {"title": "Platform Positioning", "focus": "Ecosystem advantage", "tactics": ["network effects", "integration benefits", "lock-in advantage"]},
    "positioning_015": {"title": "Sustainability Positioning", "focus": "Environmental/social benefits", "tactics": ["impact measurement", "values alignment", "certification"]},
    "positioning_016": {"title": "Quality Positioning", "focus": "Premium quality claim", "tactics": ["craftsmanship", "materials/ingredients", "longevity"]},
    "positioning_017": {"title": "Convenience Positioning", "focus": "Ease and simplicity", "tactics": ["time savings", "effort reduction", "accessibility"]},
    "positioning_018": {"title": "Reliability Positioning", "focus": "Trust and consistency", "tactics": ["track record", "testimonials", "guarantees"]},
    "positioning_019": {"title": "Innovation Positioning", "focus": "Cutting-edge narrative", "tactics": ["R&D investment", "feature firsts", "technology leadership"]},
    "positioning_020": {"title": "Service Positioning", "focus": "Support differentiation", "tactics": ["response time", "expertise", "support quality"]},
    "positioning_021": {"title": "Community Positioning", "focus": "Belonging narrative", "tactics": ["user community", "co-creation", "shared mission"]},
    "positioning_022": {"title": "Heritage Positioning", "focus": "History and tradition", "tactics": ["founding story", "legacy", "proven track record"]},
    "positioning_023": {"title": "Accessibility Positioning", "focus": "Inclusive narrative", "tactics": ["affordability", "ease of use", "universal design"]},
    "positioning_024": {"title": "Authority Positioning", "focus": "Expert leadership", "tactics": ["credentials", "thought leadership", "industry recognition"]},
    "positioning_025": {"title": "Partnership Positioning", "focus": "Collaboration advantage", "tactics": ["strategic partnerships", "ecosystem", "mutual benefit"]},

    # COMPETITIVE ADVANTAGE (25 prompts)
    "competitive_001": {"title": "Moat Analysis", "focus": "Build defensible advantages", "tactics": ["network effects", "switching costs", "brand value", "IP protection"]},
    "competitive_002": {"title": "Cost Advantage Strategy", "focus": "Win on price", "tactics": ["economies of scale", "operational efficiency", "supply chain"]},
    "competitive_003": {"title": "Differentiation Strategy", "focus": "Unique features/benefits", "tactics": ["feature uniqueness", "customer experience", "quality"]},
    "competitive_004": {"title": "Speed Advantage", "focus": "Time-to-market leadership", "tactics": ["execution speed", "innovation pace", "agility"]},
    "competitive_005": {"title": "Quality Leadership", "focus": "Superior product/service", "tactics": ["zero-defect thinking", "continuous improvement", "craftsmanship"]},
    "competitive_006": {"title": "Customer Intimacy", "focus": "Deep relationship advantage", "tactics": ["personalization", "service quality", "customer understanding"]},
    "competitive_007": {"title": "Technology Advantage", "focus": "Tech-powered differentiation", "tactics": ["proprietary technology", "AI/ML integration", "automation"]},
    "competitive_008": {"title": "Brand Advantage", "focus": "Brand equity strength", "tactics": ["brand recognition", "brand loyalty", "premium perception"]},
    "competitive_009": {"title": "Network Effects", "focus": "Two-sided platform advantage", "tactics": ["user base growth", "value multiplication", "lock-in"]},
    "competitive_010": {"title": "Data Advantage", "focus": "Data-driven edge", "tactics": ["data collection", "insights generation", "predictive capability"]},
    "competitive_011": {"title": "Market Position Advantage", "focus": "Market share strength", "tactics": ["leading position", "market share defense", "expansion leverage"]},
    "competitive_012": {"title": "Resource Advantage", "focus": "Capital and talent strength", "tactics": ["funding", "talent attraction", "investment capability"]},
    "competitive_013": {"title": "Distribution Advantage", "focus": "Channel strength", "tactics": ["channel access", "logistics network", "shelf space"]},
    "competitive_014": {"title": "Partnership Advantage", "focus": "Strategic relationships", "tactics": ["partner ecosystem", "integration partnerships", "exclusive deals"]},
    "competitive_015": {"title": "Regulatory Advantage", "focus": "Legal moat", "tactics": ["patents", "licenses", "regulatory barriers"]},
    "competitive_016": {"title": "Geographic Advantage", "focus": "Location-based edge", "tactics": ["local presence", "regional expertise", "proximity advantage"]},
    "competitive_017": {"title": "Vertical Integration", "focus": "Supply chain control", "tactics": ["supply security", "margin capture", "quality control"]},
    "competitive_018": {"title": "Ecosystem Advantage", "focus": "Surrounding support", "tactics": ["complementary products", "platform strategy", "environment creation"]},
    "competitive_019": {"title": "Talent Advantage", "focus": "Team strength", "tactics": ["top talent attraction", "expertise concentration", "thought leadership"]},
    "competitive_020": {"title": "Customer Data Advantage", "focus": "Customer intelligence edge", "tactics": ["behavior insights", "predictive modeling", "personalization"]},
    "competitive_021": {"title": "Speed-to-Scale Advantage", "focus": "Rapid growth capability", "tactics": ["scalable model", "viral mechanics", "system efficiency"]},
    "competitive_022": {"title": "Cost Structure Advantage", "focus": "Unit economics leadership", "tactics": ["automation", "leverage", "variable cost reduction"]},
    "competitive_023": {"title": "Customer Loyalty Advantage", "focus": "Retention edge", "tactics": ["churn reduction", "lifetime value", "advocacy generation"]},
    "competitive_024": {"title": "Innovation Pipeline", "focus": "Continuous improvement edge", "tactics": ["R&D intensity", "launch cadence", "feature velocity"]},
    "competitive_025": {"title": "Market Insights Advantage", "focus": "Knowledge edge", "tactics": ["market intelligence", "trend prediction", "opportunity spotting"]},

    # SALES STRATEGIES (30 prompts)
    "sales_strategy_001": {"title": "Consultative Selling", "focus": "Problem-first approach", "tactics": ["discovery questions", "need identification", "solution recommendation"]},
    "sales_strategy_002": {"title": "Solution Selling", "focus": "ROI-focused approach", "tactics": ["value quantification", "business case", "risk reduction"]},
    "sales_strategy_003": {"title": "Account-Based Marketing", "focus": "Target high-value accounts", "tactics": ["account selection", "personalization", "multi-threaded selling"]},
    "sales_strategy_004": {"title": "Land-and-Expand", "focus": "Grow existing customers", "tactics": ["small initial deal", "upsell trigger", "expansion motion"]},
    "sales_strategy_005": {"title": "Direct Sales", "focus": "Personal relationship selling", "tactics": ["sales team", "relationship building", "consultative approach"]},
    "sales_strategy_006": {"title": "Inside Sales", "focus": "Phone and video selling", "tactics": ["call efficiency", "pipeline velocity", "cost effectiveness"]},
    "sales_strategy_007": {"title": "Self-Serve Sales", "focus": "Product-led growth", "tactics": ["freemium model", "self-signup", "in-product upgrade"]},
    "sales_strategy_008": {"title": "Channel Sales", "focus": "Partner-driven revenue", "tactics": ["partner recruitment", "incentive structure", "support system"]},
    "sales_strategy_009": {"title": "Marketplace Sales", "focus": "Platform-based selling", "tactics": ["listing optimization", "review management", "algorithm optimization"]},
    "sales_strategy_010": {"title": "Affiliate Sales", "focus": "Commission-based growth", "tactics": ["affiliate recruitment", "commission structure", "affiliate support"]},
    "sales_strategy_011": {"title": "Enterprise Sales", "focus": "Large deal selling", "tactics": ["procurement navigation", "stakeholder management", "contract negotiation"]},
    "sales_strategy_012": {"title": "Mid-Market Sales", "focus": "Balance speed and relationship", "tactics": ["account team", "decision maker access", "ROI focus"]},
    "sales_strategy_013": {"title": "SMB Sales", "focus": "Volume and efficiency", "tactics": ["self-serve hybrid", "low touch", "fast decision"]},
    "sales_strategy_014": {"title": "Inbound Sales", "focus": "Lead-generated selling", "tactics": ["warm lead nurturing", "quick response", "easy buying"]},
    "sales_strategy_015": {"title": "Outbound Sales", "focus": "Prospecting-driven selling", "tactics": ["cold outreach", "pipeline creation", "persistence"]},
    "sales_strategy_016": {"title": "Event-Based Sales", "focus": "Trade show and webinar selling", "tactics": ["lead capture", "follow-up process", "relationship building"]},
    "sales_strategy_017": {"title": "Community-Based Sales", "focus": "Organic community selling", "tactics": ["community building", "peer recommendations", "thought leadership"]},
    "sales_strategy_018": {"title": "Transactional Sales", "focus": "High-volume quick sell", "tactics": ["impulse optimization", "friction reduction", "conversion rate"]},
    "sales_strategy_019": {"title": "Relationship Sales", "focus": "Long-term partnership", "tactics": ["trust building", "commitment deepening", "lifetime value"]},
    "sales_strategy_020": {"title": "Consultative Partnership", "focus": "Strategic advisor role", "tactics": ["business understanding", "proactive recommendations", "value creation"]},
    "sales_strategy_021": {"title": "Price-Led Selling", "focus": "Compete on cost", "tactics": ["price transparency", "value justification", "discount strategy"]},
    "sales_strategy_022": {"title": "Premium Selling", "focus": "Justifying higher prices", "tactics": ["luxury positioning", "exclusivity", "value proof"]},
    "sales_strategy_023": {"title": "Subscription Sales", "focus": "Recurring revenue model", "tactics": ["SaaS dynamics", "churn reduction", "expansion revenue"]},
    "sales_strategy_024": {"title": "Complex Deal Selling", "focus": "Multi-stakeholder selling", "tactics": ["consensus building", "timeline management", "risk mitigation"]},
    "sales_strategy_025": {"title": "Velocity Sales", "focus": "Speed and execution", "tactics": ["pipeline efficiency", "decision acceleration", "momentum creation"]},
    "sales_strategy_026": {"title": "Retention-Focused Sales", "focus": "Keep current customers", "tactics": ["churn prevention", "satisfaction focus", "expansion selling"]},
    "sales_strategy_027": {"title": "Win-Back Sales", "focus": "Reactivate lost customers", "tactics": ["churn analysis", "re-engagement", "special incentives"]},
    "sales_strategy_028": {"title": "Cross-Sell Strategy", "focus": "Sell related products", "tactics": ["product bundling", "upgrade path", "value stacking"]},
    "sales_strategy_029": {"title": "Upsell Strategy", "focus": "Move to higher tier", "tactics": ["usage trigger", "timing optimization", "value justification"]},
    "sales_strategy_030": {"title": "Hybrid Sales Model", "focus": "Combine multiple approaches", "tactics": ["channel mix", "customer segmentation", "resource allocation"]},

    # STRENGTH OPTIMIZATION (25 prompts)
    "strengths_001": {"title": "Amplify Core Competency", "focus": "Double down on strength", "tactics": ["specialization", "expertise deepening", "market leadership"]},
    "strengths_002": {"title": "Leverage Existing Assets", "focus": "Maximize current resources", "tactics": ["asset repurposing", "leverage points", "ROI maximization"]},
    "strengths_003": {"title": "Build Network Effects", "focus": "Strengthen through growth", "tactics": ["community building", "user growth", "value multiplication"]},
    "strengths_004": {"title": "Expand Brand Moat", "focus": "Deepen brand strength", "tactics": ["brand expansion", "category leadership", "brand loyalty"]},
    "strengths_005": {"title": "Scale Operational Efficiency", "focus": "Grow without friction", "tactics": ["process optimization", "automation", "system scaling"]},
    "strengths_006": {"title": "Talent Concentration", "focus": "Build best-in-class team", "tactics": ["talent acquisition", "team culture", "expertise concentration"]},
    "strengths_007": {"title": "Technology Moat", "focus": "Deepen tech advantage", "tactics": ["proprietary development", "IP building", "innovation pipeline"]},
    "strengths_008": {"title": "Market Position Leverage", "focus": "Use market leadership", "tactics": ["market share growth", "price power", "expansion speed"]},
    "strengths_009": {"title": "Customer Intimacy Growth", "focus": "Deepen customer relationships", "tactics": ["personalization", "service excellence", "loyalty programs"]},
    "strengths_010": {"title": "Data Advantage Expansion", "focus": "Leverage data moat", "tactics": ["data collection", "insights generation", "ML advantage"]},
    "strengths_011": {"title": "Distribution Network Growth", "focus": "Expand reach", "tactics": ["channel expansion", "logistics scaling", "market penetration"]},
    "strengths_012": {"title": "Partnership Ecosystem", "focus": "Build strategic alliances", "tactics": ["partner recruitment", "ecosystem creation", "mutual benefit"]},
    "strengths_013": {"title": "Quality Leadership Deepening", "focus": "Become quality benchmark", "tactics": ["quality standards", "certification", "recognition"]},
    "strengths_014": {"title": "Innovation Velocity", "focus": "Accelerate product development", "tactics": ["R&D investment", "feature launch cadence", "market responsiveness"]},
    "strengths_015": {"title": "Cost Leadership Expansion", "focus": "Deepen cost advantage", "tactics": ["supply chain optimization", "automation", "scale benefits"]},
    "strengths_016": {"title": "Thought Leadership Growth", "focus": "Establish market authority", "tactics": ["content creation", "speaking engagements", "media presence"]},
    "strengths_017": {"title": "Customer Advocacy Building", "focus": "Create brand evangelists", "tactics": ["case study generation", "referral program", "community engagement"]},
    "strengths_018": {"title": "Vertical Integration", "focus": "Control value chain", "tactics": ["supply acquisition", "capability building", "margin capture"]},
    "strengths_019": {"title": "Adjacent Market Entry", "focus": "Expand to related spaces", "tactics": ["market selection", "product adaptation", "go-to-market"]},
    "strengths_020": {"title": "Platform Expansion", "focus": "Build ecosystem", "tactics": ["API development", "partner integration", "network effects"]},
    "strengths_021": {"title": "Geographic Expansion", "focus": "Grow to new regions", "tactics": ["market selection", "localization", "partnership strategy"]},
    "strengths_022": {"title": "Market Share Capture", "focus": "Steal share from competitors", "tactics": ["competitive positioning", "switching incentive", "market education"]},
    "strengths_023": {"title": "Strategic Acquisition Strategy", "focus": "Buy complementary capabilities", "tactics": ["target identification", "integration planning", "synergy capture"]},
    "strengths_024": {"title": "Brand Extension", "focus": "Leverage brand to new products", "tactics": ["brand equity transfer", "product strategy", "market positioning"]},
    "strengths_025": {"title": "Operational Excellence", "focus": "Continuous improvement culture", "tactics": ["efficiency metrics", "process optimization", "waste elimination"]},

    # WEAKNESS MITIGATION (25 prompts)
    "weakness_001": {"title": "Address Cost Disadvantage", "focus": "Reduce cost gap", "tactics": ["supply chain", "automation", "efficiency", "pricing strategy"]},
    "weakness_002": {"title": "Build Brand Recognition", "focus": "Overcome brand deficit", "tactics": ["marketing investment", "PR", "thought leadership", "community"]},
    "weakness_003": {"title": "Improve Product Quality", "focus": "Close quality gap", "tactics": ["QA investment", "feature development", "customer feedback"]},
    "weakness_004": {"title": "Strengthen Sales Capability", "focus": "Build sales effectiveness", "tactics": ["team hiring", "training", "process improvement", "tools"]},
    "weakness_005": {"title": "Expand Distribution", "focus": "Overcome access limitation", "tactics": ["channel development", "partnership", "direct sales", "online"]},
    "weakness_006": {"title": "Deepen Customer Relationships", "focus": "Build loyalty and retention", "tactics": ["customer service", "personalization", "community", "support"]},
    "weakness_007": {"title": "Accelerate Innovation", "focus": "Match competitor innovation pace", "tactics": ["R&D", "partnerships", "acquisitions", "process improvement"]},
    "weakness_008": {"title": "Improve Cash Flow", "focus": "Address financial constraint", "tactics": ["revenue acceleration", "cost reduction", "financing", "working capital"]},
    "weakness_009": {"title": "Strengthen Team", "focus": "Address talent gap", "tactics": ["hiring", "training", "culture", "retention"]},
    "weakness_010": {"title": "Build Technology Capability", "focus": "Close technology gap", "tactics": ["hiring", "partnerships", "acquisitions", "outsourcing"]},
    "weakness_011": {"title": "Improve Market Intelligence", "focus": "Better understand market", "tactics": ["research", "customer interviews", "competitive analysis", "data"]},
    "weakness_012": {"title": "Address Geographic Limitation", "focus": "Expand to new regions", "tactics": ["partnerships", "hiring", "investment", "localization"]},
    "weakness_013": {"title": "Overcome Regulatory Barrier", "focus": "Navigate compliance", "tactics": ["legal", "partnerships", "lobbying", "adaptation"]},
    "weakness_014": {"title": "Build Strategic Partnerships", "focus": "Leverage partner strengths", "tactics": ["partner identification", "negotiation", "integration", "support"]},
    "weakness_015": {"title": "Improve Customer Experience", "focus": "Close experience gap", "focus": "Close experience gap", "tactics": ["design", "support", "feedback", "iteration"]},
    "weakness_016": {"title": "Address Scalability Issues", "focus": "Enable growth", "tactics": ["infrastructure", "process", "team", "outsourcing"]},
    "weakness_017": {"title": "Build Data Infrastructure", "focus": "Leverage data advantage", "tactics": ["analytics", "database", "ML", "hiring"]},
    "weakness_018": {"title": "Improve Operational Efficiency", "focus": "Reduce friction", "tactics": ["process", "automation", "outsourcing", "optimization"]},
    "weakness_019": {"title": "Strengthen Marketing", "focus": "Address marketing gap", "tactics": ["team", "investment", "partnerships", "channels"]},
    "weakness_020": {"title": "Build Executive Team", "focus": "Address leadership gap", "tactics": ["hiring", "advisors", "mentorship", "development"]},
    "weakness_021": {"title": "Improve Product-Market Fit", "focus": "Better serve customers", "tactics": ["customer research", "product iteration", "positioning", "messaging"]},
    "weakness_022": {"title": "Address Supply Chain Risk", "focus": "Ensure reliability", "tactics": ["diversification", "inventory", "partnerships", "integration"]},
    "weakness_023": {"title": "Build Customer Success", "focus": "Improve retention", "tactics": ["team", "process", "tools", "accountability"]},
    "weakness_024": {"title": "Improve Financial Planning", "focus": "Better forecast and plan", "tactics": ["process", "tools", "expertise", "discipline"]},
    "weakness_025": {"title": "Address Reputation Risk", "focus": "Protect brand", "tactics": ["communication", "action", "transparency", "recovery"]},

    # CUSTOMER PSYCHOLOGY (20 prompts)
    "psychology_001": {"title": "Trust Building Tactics", "focus": "Establish credibility", "tactics": ["testimonials", "case studies", "guarantees", "proof"]},
    "psychology_002": {"title": "Social Proof Leverage", "focus": "Use peer influence", "tactics": ["testimonials", "case studies", "media coverage", "numbers"]},
    "psychology_003": {"title": "FOMO Activation", "focus": "Tap into fear of missing out", "tactics": ["scarcity", "limited time", "exclusive access", "urgency"]},
    "psychology_004": {"title": "Authority Positioning", "focus": "Establish expert status", "tactics": ["credentials", "media", "speaking", "thought leadership"]},
    "psychology_005": {"title": "Reciprocity Principle", "focus": "Give before you ask", "tactics": ["free value", "freemium", "trial", "free sample"]},
    "psychology_006": {"title": "Commitment and Consistency", "focus": "Small commitments lead to bigger", "tactics": ["email signup", "free trial", "small purchase", "progression"]},
    "psychology_007": {"title": "Liking and Similarity", "focus": "Connect on personal level", "tactics": ["relatability", "shared values", "personality", "community"]},
    "psychology_008": {"title": "Authority and Expertise", "focus": "Position as expert", "tactics": ["certifications", "experience", "results", "recognition"]},
    "psychology_009": {"title": "Price Anchoring", "focus": "Set reference price", "tactics": ["comparison", "original price", "tiering", "premium positioning"]},
    "psychology_010": {"title": "Loss Aversion", "focus": "Fear of losing more than gaining", "tactics": ["risk reversal", "guarantee", "money-back", "trial"]},
    "psychology_011": {"title": "Status Motivation", "focus": "Appeal to status seeking", "tactics": ["premium positioning", "exclusivity", "luxury", "recognition"]},
    "psychology_012": {"title": "Belonging Motivation", "focus": "Appeal to community need", "tactics": ["community", "shared identity", "belonging", "shared mission"]},
    "psychology_013": {"title": "Achievement Motivation", "focus": "Appeal to accomplishment desire", "tactics": ["results focus", "progress tracking", "success stories", "transformation"]},
    "psychology_014": {"title": "Security Motivation", "focus": "Appeal to safety seeking", "tactics": ["reliability", "guarantees", "support", "peace of mind"]},
    "psychology_015": {"title": "Freedom Motivation", "focus": "Appeal to autonomy", "tactics": ["customization", "control", "flexibility", "user agency"]},
    "psychology_016": {"title": "Fairness Principle", "focus": "Appeal to justice", "tactics": ["transparent pricing", "equal treatment", "ethical practices", "sustainability"]},
    "psychology_017": {"title": "Default Bias Exploitation", "focus": "Use defaults wisely", "tactics": ["opt-out not opt-in", "recommended option", "presales", "pre-selected"]},
    "psychology_018": {"title": "Availability Heuristic", "focus": "Make benefits memorable", "tactics": ["repetition", "stories", "examples", "salience"]},
    "psychology_019": {"title": "Anchoring Bias", "focus": "First number sticks", "tactics": ["high anchor", "initial offer", "reference point", "comparison"]},
    "psychology_020": {"title": "Sunk Cost Recovery", "focus": "Continuation after investment", "tactics": ["learning journey", "progression", "investment protection", "lock-in"]},

    # PRICE OPTIMIZATION (15 prompts)
    "pricing_001": {"title": "Value-Based Pricing", "focus": "Price by value delivered", "tactics": ["ROI calculation", "value quantification", "willingness to pay", "premium pricing"]},
    "pricing_002": {"title": "Dynamic Pricing", "focus": "Adjust by market conditions", "tactics": ["demand-based", "seasonality", "inventory", "competition"]},
    "pricing_003": {"title": "Psychological Pricing", "focus": "Exploit price psychology", "tactics": ["charm pricing", "anchoring", "bundling", "tiering"]},
    "pricing_004": {"title": "Tiered Pricing Strategy", "focus": "Segment by willingness to pay", "tactics": ["basic/pro/enterprise", "feature gating", "customer segmentation", "upsell"]},
    "pricing_005": {"title": "Cost-Plus Pricing", "focus": "Price above cost", "tactics": ["margin setting", "cost tracking", "profitability", "competitive awareness"]},
    "pricing_006": {"title": "Competitive Pricing", "focus": "Price against competitors", "tactics": ["parity pricing", "undercut strategy", "premium positioning", "monitoring"]},
    "pricing_007": {"title": "Subscription Pricing", "focus": "Recurring revenue model", "tactics": ["monthly/annual", "discount incentive", "retention", "expansion"]},
    "pricing_008": {"title": "Freemium Pricing", "focus": "Free + premium model", "tactics": ["free tier limits", "upgrade trigger", "conversion optimization", "retention"]},
    "pricing_009": {"title": "Pay-Per-Use Pricing", "focus": "Charge by usage", "tactics": ["usage tracking", "cost predictability", "overage handling", "transparency"]},
    "pricing_010": {"title": "Volume Discounting", "focus": "Reward bulk purchases", "tactics": ["quantity tiers", "annual discount", "enterprise deal", "lock-in"]},
    "pricing_011": {"title": "Premium Pricing", "focus": "High-price positioning", "tactics": ["quality positioning", "exclusivity", "luxury branding", "value emphasis"]},
    "pricing_012": {"title": "Penetration Pricing", "focus": "Low price for adoption", "tactics": ["market share", "customer acquisition", "later price increase", "network effects"]},
    "pricing_013": {"title": "Bundling Strategy", "focus": "Combine products for value", "tactics": ["package creation", "value enhancement", "margin", "customer value"]},
    "pricing_014": {"title": "Price Increase Strategy", "focus": "Raise prices without losing customers", "tactics": ["communication", "timing", "value reinforcement", "grandfathering"]},
    "pricing_015": {"title": "Discount Strategy", "focus": "Strategic discounting", "tactics": ["timing", "targeting", "seasonality", "promotional", "retention"]},

    # GROWTH MECHANICS (15 prompts)
    "growth_001": {"title": "Viral Coefficient Optimization", "focus": "User-driven referral growth", "tactics": ["network effects", "virality coefficient", "incentive structure", "shareability"]},
    "growth_002": {"title": "Content Marketing Flywheel", "focus": "Build organic traffic engine", "tactics": ["SEO", "content strategy", "distribution", "conversion"]},
    "growth_003": {"title": "Retention-Driven Growth", "focus": "Grow through customer success", "tactics": ["churn reduction", "LTV maximization", "upsell", "community"]},
    "growth_004": {"title": "Product-Led Growth", "focus": "Product drives adoption", "tactics": ["freemium", "self-serve", "in-product education", "viral features"]},
    "growth_005": {"title": "Partner-Driven Growth", "focus": "Leverage partner ecosystem", "tactics": ["channel partnerships", "affiliate", "reseller", "integration partners"]},
    "growth_006": {"title": "Paid Acquisition Scaling", "focus": "Scale ads profitably", "tactics": ["CAC optimization", "LTV improvement", "channel mix", "unit economics"]},
    "growth_007": {"title": "Sales-Driven Growth", "focus": "Enterprise sales motion", "tactics": ["account selection", "sales team", "sales cycles", "deal size"]},
    "growth_008": {"title": "Community-Driven Growth", "focus": "Community as growth engine", "tactics": ["community building", "peer recommendations", "advocacy", "organic word-of-mouth"]},
    "growth_009": {"title": "Brand-Driven Growth", "focus": "Build brand moat", "tactics": ["brand recognition", "PR", "thought leadership", "media coverage"]},
    "growth_010": {"title": "Market Expansion", "focus": "Enter new markets", "tactics": ["market selection", "go-to-market", "localization", "partnership"]},
    "growth_011": {"title": "Expansion Revenue", "focus": "Grow existing customer value", "tactics": ["upsell", "cross-sell", "add-ons", "seat growth"]},
    "growth_012": {"title": "Network Effects Activation", "focus": "Two-sided marketplace growth", "tactics": ["critical mass", "supply/demand balance", "platform strategy", "moat building"]},
    "growth_013": {"title": "SEO and Organic Growth", "focus": "Long-term organic traffic", "tactics": ["keyword strategy", "content creation", "link building", "technical SEO"]},
    "growth_014": {"title": "Direct Mail / Guerrilla Marketing", "focus": "Unconventional high-impact", "tactics": ["local activation", "PR stunts", "sampling", "grassroots"]},
    "growth_015": {"title": "Retention and Win-Back", "focus": "Reactivate and retain", "tactics": ["churn prevention", "win-back campaigns", "loyalty programs", "engagement"]},
}

# Injector function for SellIA brain
def load_comprehensive_prompts() -> dict:
    """Load 200 comprehensive sales prompts into SellIA brain."""
    return COMPREHENSIVE_PROMPTS
