"""350 Expert Voices Prompts — Sales, Marketing, Persuasion, Negotiation, Innovation, Strategy"""

EXPERT_PROMPTS = {
    # DONALD TRUMP (18 prompts)
    "trump_001": {"expert": "Trump", "voice": "Deal-Making", "focus": "Negotiation advantage", "principle": "Negotiate from strength, always have leverage, never show desperation"},
    "trump_002": {"expert": "Trump", "voice": "Brand Dominance", "focus": "Personal brand power", "principle": "Build brand bigger than product, use media relentlessly, brand is money"},
    "trump_003": {"expert": "Trump", "voice": "Winner Mindset", "focus": "Competitive edge", "principle": "Think big, set impossible goals, winners don't settle"},
    "trump_004": {"expert": "Trump", "voice": "Location Strategy", "focus": "Strategic positioning", "principle": "Prime location/market beats mediocre product, real estate is leverage"},
    "trump_005": {"expert": "Trump", "voice": "Debt as Tool", "focus": "Capital leverage", "principle": "Use other people's money, debt is opportunity if managed right"},
    "trump_006": {"expert": "Trump", "voice": "Value Perception", "focus": "Luxury positioning", "principle": "Luxury sells premium, scarcity drives demand, exclusivity is worth more"},
    "trump_007": {"expert": "Trump", "voice": "Timing Mastery", "focus": "Market timing", "principle": "Buy low/sell high, timing beats everything, patience wins"},
    "trump_008": {"expert": "Trump", "voice": "Media Strategy", "focus": "Publicity generation", "principle": "All publicity is good, controversy generates engagement, free press matters"},
    "trump_009": {"expert": "Trump", "voice": "Competition Ruthlessness", "focus": "Market dominance", "principle": "Crush competition, make them irrelevant, winner takes all"},
    "trump_010": {"expert": "Trump", "voice": "Deal Structure", "focus": "Win-win illusion", "principle": "Structure deals where you win more, control terms, favorable outcomes"},
    "trump_011": {"expert": "Trump", "voice": "Bankruptcy Strategy", "focus": "Risk management", "principle": "Bankruptcy isn't failure, strategic asset protection, start again bigger"},
    "trump_012": {"expert": "Trump", "voice": "Employee Quality", "focus": "Team excellence", "principle": "Hire the best, pay top dollar, surround yourself with winners"},
    "trump_013": {"expert": "Trump", "voice": "Instinct Trust", "focus": "Gut feel decisions", "principle": "Trust gut instinct, emotion beats analysis sometimes, quick decisions win"},
    "trump_014": {"expert": "Trump", "voice": "Persistence Obsession", "focus": "Never quit", "principle": "Never admit defeat, push harder, comeback is bigger than fall"},
    "trump_015": {"expert": "Trump", "voice": "Spectacle Marketing", "focus": "Grandeur selling", "principle": "Make it big, make it dramatic, make people talk"},
    "trump_016": {"expert": "Trump", "voice": "Renegotiation Skill", "focus": "Deal improvement", "principle": "Renegotiate constantly, improve terms mid-deal, never accept initial offer"},
    "trump_017": {"expert": "Trump", "voice": "Visibility Obsession", "focus": "Constant presence", "principle": "Stay visible, always in news, top of mind wins"},
    "trump_018": {"expert": "Trump", "voice": "Product is Secondary", "focus": "Brand over product", "principle": "Brand drives sales not quality, reputation matters most, brand equity is asset"},

    # JORDAN BELFORT (18 prompts)
    "belfort_001": {"expert": "Belfort", "voice": "Urgency Injection", "focus": "Pressure selling", "principle": "Create urgency, limited time offers, scarcity psychology"},
    "belfort_002": {"expert": "Belfort", "voice": "Assumptive Close", "focus": "Take the deal", "principle": "Assume yes, speak as if sold, confidence sells"},
    "belfort_003": {"expert": "Belfort", "voice": "Objection Handling", "focus": "Turn no to yes", "principle": "Never accept no, reframe objections, find hidden wants"},
    "belfort_004": {"expert": "Belfort", "voice": "Rapport Building", "focus": "Connection mastery", "principle": "Mirror body language, find common ground, people buy from friends"},
    "belfort_005": {"expert": "Belfort", "voice": "Pain Point Extraction", "focus": "Problem discovery", "principle": "Ask deep questions, uncover real pain, solution flows from pain"},
    "belfort_006": {"expert": "Belfort", "voice": "Energy Elevation", "focus": "Contagious enthusiasm", "principle": "Energy is contagious, enthusiasm sells, fake it till you make it"},
    "belfort_007": {"expert": "Belfort", "voice": "Commitment Progression", "focus": "Small yeses", "principle": "Start with small commitments, build to big ones, yes momentum"},
    "belfort_008": {"expert": "Belfort", "voice": "Social Proof Explosion", "focus": "Peer pressure selling", "principle": "Everyone wants it, people joining daily, FOMO is real"},
    "belfort_009": {"expert": "Belfort", "voice": "Product Story Mastery", "focus": "Storytelling power", "principle": "Story connects emotions, product is hero, buyer is hero"},
    "belfort_010": {"expert": "Belfort", "voice": "Persistence Over Process", "focus": "Relentless follow-up", "principle": "Follow up constantly, don't give up, persistence breaks resistance"},
    "belfort_011": {"expert": "Belfort", "voice": "Tonality Power", "focus": "Voice control", "principle": "Tonality matters more than words, control tone control outcome"},
    "belfort_012": {"expert": "Belfort", "voice": "Pupil Dilation Mastery", "focus": "Reading desire", "principle": "Watch eyes, read emotional state, desire shows in physiology"},
    "belfort_013": {"expert": "Belfort", "voice": "Positioning as Solution", "focus": "Problem solver frame", "principle": "Position as savior, solve their problem, be the hero"},
    "belfort_014": {"expert": "Belfort", "voice": "Scarcity Mastery", "focus": "Limited supply", "principle": "Create scarcity, limited time, limited quantity, fear losing"},
    "belfort_015": {"expert": "Belfort", "voice": "Payment Elimination", "focus": "Deal with money", "principle": "Never focus on price, value over cost, easy payment plans"},
    "belfort_016": {"expert": "Belfort", "voice": "Confidence as Currency", "focus": "Belief projection", "principle": "Believe in product first, belief is contagious, doubt kills sales"},
    "belfort_017": {"expert": "Belfort", "voice": "Reframing Mastery", "focus": "Perspective shift", "principle": "Reframe objections as benefits, change how they see problem"},
    "belfort_018": {"expert": "Belfort", "voice": "Team Momentum", "focus": "Group energy", "principle": "Momentum in team, celebrate wins openly, energy spreads"},

    # WARREN BUFFETT (18 prompts)
    "buffett_001": {"expert": "Buffett", "voice": "Value Discovery", "focus": "True value finding", "principle": "Find intrinsic value, market inefficiency is opportunity, patience wins"},
    "buffett_002": {"expert": "Buffett", "voice": "Moat Building", "focus": "Competitive advantage", "principle": "Build moats, sustainable advantage, defensibility matters"},
    "buffett_003": {"expert": "Buffett", "voice": "Long-term Thinking", "focus": "Permanent hold", "principle": "Think decades not quarters, compound interest dominates, patience pays"},
    "buffett_004": {"expert": "Buffett", "voice": "Simplicity", "focus": "Understandable business", "principle": "Only invest if you understand it, complexity hides problems"},
    "buffett_005": {"expert": "Buffett", "voice": "Management Quality", "focus": "Team matters", "principle": "Manager quality defines success, honest operators outperform"},
    "buffett_006": {"expert": "Buffett", "voice": "Margin of Safety", "focus": "Risk protection", "principle": "Protect downside, margin of safety, never overpay"},
    "buffett_007": {"expert": "Buffett", "voice": "Cash Flow Focus", "focus": "Money movement", "principle": "Cash flow over earnings, cash is king, numbers don't lie"},
    "buffett_008": {"expert": "Buffett", "voice": "Dividend Power", "focus": "Passive income", "principle": "Dividends compound wealth, reinvest dividends, passive growth"},
    "buffett_009": {"expert": "Buffett", "voice": "Market Timing Irrelevance", "focus": "Time in market", "principle": "Timing beats timing never, stay invested, don't panic sell"},
    "buffett_010": {"expert": "Buffett", "voice": "Opportunity Patience", "focus": "Selective investing", "principle": "Wait for fat pitches, selective investing, quality over quantity"},
    "buffett_011": {"expert": "Buffett", "voice": "Debt Warning", "focus": "Financial risk", "principle": "Avoid debt, stay solvent, leverage is dangerous"},
    "buffett_012": {"expert": "Buffett", "voice": "Circle of Competence", "focus": "Expertise boundary", "principle": "Know your edge, don't chase unknowns, master your domain"},
    "buffett_013": {"expert": "Buffett", "voice": "Earnings Quality", "focus": "Real profits", "principle": "Real earnings matter, accounting tricks don't fool fundamentals"},
    "buffett_014": {"expert": "Buffett", "voice": "Buyback Strategy", "focus": "Share reduction", "principle": "Buybacks increase value, reduce shares outstanding, unlock value"},
    "buffett_015": {"expert": "Buffett", "voice": "Industry Selection", "focus": "Choosing sectors", "principle": "Pick growing industries, avoid decline sectors, tailwinds matter"},
    "buffett_016": {"expert": "Buffett", "voice": "Reputation Protection", "focus": "Character building", "principle": "Character is legacy, protect reputation, one-time losses hurt forever"},
    "buffett_017": {"expert": "Buffett", "voice": "Continuous Learning", "focus": "Knowledge pursuit", "principle": "Read voraciously, learn constantly, knowledge is advantage"},
    "buffett_018": {"expert": "Buffett", "voice": "Generosity Strategy", "focus": "Giving wealth", "principle": "Give away wealth, philanthropy matters, success means responsibility"},

    # ROBERT KIYOSAKI (18 prompts)
    "kiyosaki_001": {"expert": "Kiyosaki", "voice": "Asset vs Liability", "focus": "Wealth definition", "principle": "Assets put money in pocket, liabilities take money out, buy assets"},
    "kiyosaki_002": {"expert": "Kiyosaki", "voice": "Cash Flow vs Capital Gains", "focus": "Income streams", "principle": "Focus cash flow not appreciation, monthly income beats home value"},
    "kiyosaki_003": {"expert": "Kiyosaki", "voice": "Passive Income", "focus": "Time freedom", "principle": "Create passive income, let money work for you, escape rat race"},
    "kiyosaki_004": {"expert": "Kiyosaki", "voice": "Real Estate Leverage", "focus": "Property investing", "principle": "Real estate is leverage, other people's money builds wealth"},
    "kiyosaki_005": {"expert": "Kiyosaki", "voice": "Tax Advantages", "focus": "Legal tax avoidance", "principle": "Rich use tax law, business owners pay less, structure matters"},
    "kiyosaki_006": {"expert": "Kiyosaki", "voice": "Financial Independence", "focus": "Freedom target", "principle": "Get passive income above expenses, financial independence is goal"},
    "kiyosaki_007": {"expert": "Kiyosaki", "voice": "Multiple Income Streams", "focus": "Diversification", "principle": "One income is risky, multiple streams reduce risk, layer income"},
    "kiyosaki_008": {"expert": "Kiyosaki", "voice": "Business Creation", "focus": "Enterprise building", "principle": "Build business systems, create jobs, business is wealth multiplier"},
    "kiyosaki_009": {"expert": "Kiyosaki", "voice": "Debt Strategy", "focus": "Good vs bad debt", "principle": "Good debt builds wealth, bad debt consumes, leverage wisely"},
    "kiyosaki_010": {"expert": "Kiyosaki", "voice": "Education ROI", "focus": "Learning investment", "principle": "Financial education beats college, learn about money early"},
    "kiyosaki_011": {"expert": "Kiyosaki", "voice": "Opportunity Recognition", "focus": "Deal spotting", "principle": "See deals others miss, market inefficiencies create wealth"},
    "kiyosaki_012": {"expert": "Kiyosaki", "voice": "Risk Management", "focus": "Downside protection", "principle": "Protect downside, insure against loss, don't gamble"},
    "kiyosaki_013": {"expert": "Kiyosaki", "voice": "Mentorship Importance", "focus": "Learn from success", "principle": "Find mentors, learn from rich not poor, experience transfers"},
    "kiyosaki_014": {"expert": "Kiyosaki", "voice": "Mindset Shift", "focus": "Poor vs rich thinking", "principle": "Rich think differently, abundance mindset attracts wealth"},
    "kiyosaki_015": {"expert": "Kiyosaki", "voice": "Networking Power", "focus": "Rich relationships", "principle": "Network with rich people, your net worth is average of 5 closest"},
    "kiyosaki_016": {"expert": "Kiyosaki", "voice": "Self-Employment Freedom", "focus": "Own business journey", "principle": "Self-employment builds wealth, employee status limits growth"},
    "kiyosaki_017": {"expert": "Kiyosaki", "voice": "Systems and Leverage", "focus": "Scaling wealth", "principle": "Systems scale beyond you, leverage is key to big wealth"},
    "kiyosaki_018": {"expert": "Kiyosaki", "voice": "Cash Machine Creation", "focus": "Business as asset", "principle": "Business systems print cash, passive income is freedom"},

    # ALEX HORMOZI + GRANT CARDONE (18 prompts combined)
    "hormozi_001": {"expert": "Hormozi", "voice": "Value Stack", "focus": "Offer design", "principle": "Stack value layer by layer, perceived value matters most"},
    "hormozi_002": {"expert": "Hormozi", "voice": "Pricing Power", "focus": "Price increase", "principle": "Raise prices, charge premium, quality commands premium"},
    "hormozi_003": {"expert": "Hormozi", "voice": "Offer Design", "focus": "Irresistible offer", "principle": "Design offers hard to refuse, clear value proposition wins"},
    "hormozi_004": {"expert": "Hormozi", "voice": "Scalability Focus", "focus": "Growth systems", "principle": "Build scalable systems, own time becomes others' time"},
    "hormozi_005": {"expert": "Hormozi", "voice": "Acquisition Strategy", "focus": "Customer getting", "principle": "Master acquisition, customer acquisition is all that matters"},
    "hormozi_006": {"expert": "Hormozi", "voice": "Retention Mastery", "focus": "Keep customers", "principle": "Retention is cheaper than acquisition, keep customers alive"},
    "hormozi_007": {"expert": "Hormozi", "voice": "Revenue Growth", "focus": "Increase income", "principle": "Increase revenue systematically, operations follow demand"},
    "hormozi_008": {"expert": "Hormozi", "voice": "Network Effect", "focus": "Community value", "principle": "Build network, network increases value exponentially"},
    "hormozi_009": {"expert": "Hormozi", "voice": "Problem-Solution Fit", "focus": "Market need", "principle": "Solve real problems, people pay for solutions"},
    "cardone_010": {"expert": "Cardone", "voice": "10X Thinking", "focus": "Massive goals", "principle": "Think 10X not 2X, stretch goals create stretch performance"},
    "cardone_011": {"expert": "Cardone", "voice": "Obsessive Action", "focus": "Massive activity", "principle": "Massive action beats perfect planning, do more than anyone else"},
    "cardone_012": {"expert": "Cardone", "voice": "No Excuses", "focus": "Accountability", "principle": "Own your results, excuses kill success, play to win always"},
    "cardone_013": {"expert": "Cardone", "voice": "Competing Fiercely", "focus": "Win mentality", "principle": "Competition drives growth, compete like your life depends on it"},
    "cardone_014": {"expert": "Cardone", "voice": "Customer Obsession", "focus": "Client focus", "principle": "Obsess about customers, customer satisfaction drives success"},
    "cardone_015": {"expert": "Cardone", "voice": "Money Hunger", "focus": "Revenue focus", "principle": "Stay hungry for money, ambition fuels growth"},
    "cardone_016": {"expert": "Cardone", "voice": "Status and Wealth", "focus": "Success symbols", "principle": "Success is visible, flaunt it, inspire others"},
    "cardone_017": {"expert": "Cardone", "voice": "Constant Learning", "focus": "Skill development", "principle": "Never stop learning, invest in self education"},
    "cardone_018": {"expert": "Cardone", "voice": "Pressure Handling", "focus": "Stress mastery", "principle": "Thrive under pressure, pressure creates diamonds"},

    # TONY ROBBINS (18 prompts)
    "robbins_001": {"expert": "Robbins", "voice": "Peak State", "focus": "Optimal performance", "principle": "Create peak state, physiology affects psychology"},
    "robbins_002": {"expert": "Robbins", "voice": "Goal Certainty", "focus": "Clarity on goals", "principle": "Know exact goals, specificity drives achievement"},
    "robbins_003": {"expert": "Robbins", "voice": "Identity Shift", "focus": "Become who you need", "principle": "Change identity before behavior, identity drives action"},
    "robbins_004": {"expert": "Robbins", "voice": "Belief Creation", "focus": "Empowering beliefs", "principle": "Beliefs shape reality, change beliefs change results"},
    "robbins_005": {"expert": "Robbins", "voice": "Value Elicitation", "focus": "Discovery process", "principle": "Uncover core values, values guide decisions"},
    "robbins_006": {"expert": "Robbins", "voice": "Modeling Success", "focus": "Copy winners", "principle": "Model successful people, emulate their strategies"},
    "robbins_007": {"expert": "Robbins", "voice": "Resource Activation", "focus": "Use existing skills", "principle": "Tap existing resources, you have more than you think"},
    "robbins_008": {"expert": "Robbins", "voice": "Psychological Leverage", "focus": "Motivation factors", "principle": "Use pain/pleasure leverage, motivation is choice"},
    "robbins_009": {"expert": "Robbins", "voice": "Question Power", "focus": "Better questions", "principle": "Better questions create better answers"},
    "robbins_010": {"expert": "Robbins", "voice": "Empowerment Focus", "focus": "Personal power", "principle": "Empower others, serve with intention"},
    "robbins_011": {"expert": "Robbins", "voice": "Relationship Mastery", "focus": "Connection skills", "principle": "Great relationships, understand communication styles"},
    "robbins_012": {"expert": "Robbins", "voice": "Financial Freedom", "focus": "Wealth creation", "principle": "Money is result of value, create value systematically"},
    "robbins_013": {"expert": "Robbins", "voice": "Decision Quality", "focus": "Strategic choices", "principle": "Better decisions change life, decide once commit fully"},
    "robbins_014": {"expert": "Robbins", "voice": "Dissociation Power", "focus": "Emotional detachment", "principle": "Control emotional state, choose your emotions"},
    "robbins_015": {"expert": "Robbins", "voice": "Commitment Mastery", "focus": "Total dedication", "principle": "Commit fully, total commitment creates results"},
    "robbins_016": {"expert": "Robbins", "voice": "Momentum Creation", "focus": "Building energy", "principle": "Create momentum, momentum creates success"},
    "robbins_017": {"expert": "Robbins", "voice": "Service Principle", "focus": "Contribution mindset", "principle": "Serve massively, service creates wealth"},
    "robbins_018": {"expert": "Robbins", "voice": "Ritual Power", "focus": "Daily habits", "principle": "Rituals shape life, anchor empowering rituals"},

    # GARY VEE (18 prompts)
    "garyvee_001": {"expert": "GaryVee", "voice": "Jab Jab Right Hook", "focus": "Content strategy", "principle": "Give value first, build trust, then sell"},
    "garyvee_002": {"expert": "GaryVee", "voice": "Macro Patience", "focus": "Long-term vision", "principle": "Patience with big vision, build for years not quarters"},
    "garyvee_003": {"expert": "GaryVee", "voice": "Micro Execution", "focus": "Daily detail", "principle": "Execute daily details, small actions compound"},
    "garyvee_004": {"expert": "GaryVee", "voice": "Platform Diversity", "focus": "Channel mix", "principle": "Diversify platforms, don't depend on one algorithm"},
    "garyvee_005": {"expert": "GaryVee", "voice": "Document Don't Create", "focus": "Authentic content", "principle": "Document your journey, authenticity beats production"},
    "garyvee_006": {"expert": "GaryVee", "voice": "Attention Economy", "focus": "Attention capture", "principle": "Attention is currency, capture it relentlessly"},
    "garyvee_007": {"expert": "GaryVee", "voice": "Storytelling Mastery", "focus": "Narrative power", "principle": "Tell stories not facts, stories sell"},
    "garyvee_008": {"expert": "GaryVee", "voice": "Personal Brand", "focus": "You are brand", "principle": "Brand yourself, personal brand is asset"},
    "garyvee_009": {"expert": "GaryVee", "voice": "Community Building", "focus": "Audience loyalty", "principle": "Build community, community is loyal"},
    "garyvee_010": {"expert": "GaryVee", "voice": "Emotional Intelligence", "focus": "EQ mastery", "principle": "EQ beats IQ, understand emotions"},
    "garyvee_011": {"expert": "GaryVee", "voice": "Gratitude Practice", "focus": "Appreciation mindset", "principle": "Appreciate what you have, gratitude opens doors"},
    "garyvee_012": {"expert": "GaryVee", "voice": "Patience Hustle", "focus": "Long work sprint", "principle": "Hustle hard, patience with results, compound effort"},
    "garyvee_013": {"expert": "GaryVee", "voice": "Trend Following", "focus": "Wave riding", "principle": "Follow trends, ride waves, timing matters"},
    "garyvee_014": {"expert": "GaryVee", "voice": "Competitor Analysis", "focus": "Learn from others", "principle": "Study competitors, steal ideas ethically"},
    "garyvee_015": {"expert": "GaryVee", "voice": "Ambition Channeling", "focus": "Direct energy", "principle": "Channel ambition productively, compete with self"},
    "garyvee_016": {"expert": "GaryVee", "voice": "Context Mastery", "focus": "Platform awareness", "principle": "Understand platform context, adapt message"},
    "garyvee_017": {"expert": "GaryVee", "voice": "Feedback Integration", "focus": "Learn from audience", "principle": "Listen to feedback, iterate constantly"},
    "garyvee_018": {"expert": "GaryVee", "voice": "Giving First", "focus": "Value provisioning", "principle": "Give massive value first, sales follow naturally"},

    # RAY DALIO (17 prompts)
    "dalio_001": {"expert": "Dalio", "voice": "Radical Transparency", "focus": "Open truth", "principle": "Truth over comfort, radical transparency builds trust"},
    "dalio_002": {"expert": "Dalio", "voice": "Principles Development", "focus": "System building", "principle": "Create principles, principles scale you"},
    "dalio_003": {"expert": "Dalio", "voice": "Reality Facing", "focus": "Accept reality", "principle": "Face reality head-on, denial kills businesses"},
    "dalio_004": {"expert": "Dalio", "voice": "Idea Meritocracy", "focus": "Best ideas win", "principle": "Best ideas win, hierarchy of ideas not people"},
    "dalio_005": {"expert": "Dalio", "voice": "Debt Cycles", "focus": "Debt understanding", "principle": "Understand debt cycles, manage leverage carefully"},
    "dalio_006": {"expert": "Dalio", "voice": "Economic Archetypes", "focus": "History patterns", "principle": "History repeats, patterns guide decisions"},
    "dalio_007": {"expert": "Dalio", "voice": "Diversification Science", "focus": "Portfolio balance", "principle": "Diversify for stability, reduce single-point risk"},
    "dalio_008": {"expert": "Dalio", "voice": "Decision Making Systems", "focus": "Process over luck", "principle": "Systems beat luck, repeatable process wins"},
    "dalio_009": {"expert": "Dalio", "voice": "Mistakes Value", "focus": "Learning tool", "principle": "Mistakes are education, learn from failure"},
    "dalio_010": {"expert": "Dalio", "voice": "Team Diversity", "focus": "Perspective mix", "principle": "Diverse teams solve problems better"},
    "dalio_011": {"expert": "Dalio", "voice": "Ego Management", "focus": "Personal bias", "principle": "Manage ego, check your biases"},
    "dalio_012": {"expert": "Dalio", "voice": "Evolution Perspective", "focus": "Change acceptance", "principle": "Embrace change, evolution is constant"},
    "dalio_013": {"expert": "Dalio", "voice": "Mission Clarity", "focus": "Purpose definition", "principle": "Clear mission, mission guides decisions"},
    "dalio_014": {"expert": "Dalio", "voice": "Work Culture", "focus": "Environment design", "principle": "Design culture, culture drives performance"},
    "dalio_015": {"expert": "Dalio", "voice": "Quality Focus", "focus": "Excellence standard", "principle": "Obsess quality, quality is non-negotiable"},
    "dalio_016": {"expert": "Dalio", "voice": "Feedback Loops", "focus": "Continuous learning", "principle": "Create feedback loops, iterate constantly"},
    "dalio_017": {"expert": "Dalio", "voice": "Purpose Alignment", "focus": "Values consistency", "principle": "Align purpose with actions, authenticity matters"},

    # JEREMY MINER (17 prompts)
    "miner_001": {"expert": "Miner", "voice": "Sales DNA Method", "focus": "Consultative sales", "principle": "Ask questions first, understand needs deeply"},
    "miner_002": {"expert": "Miner", "voice": "Problem Uncovering", "focus": "Need discovery", "principle": "Uncover hidden problems, surface all pain points"},
    "miner_003": {"expert": "Miner", "voice": "Active Listening", "focus": "Hear not just talk", "principle": "Listen more than speak, understanding wins sales"},
    "miner_004": {"expert": "Miner", "voice": "Positioning Mastery", "focus": "Strategic position", "principle": "Position as expert advisor, not just salesperson"},
    "miner_005": {"expert": "Miner", "voice": "Framework Selling", "focus": "Structured approach", "principle": "Use frameworks, frameworks scale success"},
    "miner_006": {"expert": "Miner", "voice": "Rapport Building", "focus": "Human connection", "principle": "Build genuine rapport, relationship drives sales"},
    "miner_007": {"expert": "Miner", "voice": "Value Articulation", "focus": "Clear benefits", "principle": "Articulate value clearly, specificity sells"},
    "miner_008": {"expert": "Miner", "voice": "Rejection Handling", "focus": "Objection mastery", "principle": "Handle rejection gracefully, test their interest"},
    "miner_009": {"expert": "Miner", "voice": "Follow-Up Persistence", "focus": "Stay engaged", "principle": "Follow-up repeatedly, persistence wins"},
    "miner_010": {"expert": "Miner", "voice": "Qualifying Buyers", "focus": "Time efficiency", "principle": "Qualify early, only pursue viable buyers"},
    "miner_011": {"expert": "Miner", "voice": "Pipeline Discipline", "focus": "Process adherence", "principle": "Manage pipeline strictly, process beats talent"},
    "miner_012": {"expert": "Miner", "voice": "Goal Setting", "focus": "Target clarity", "principle": "Set clear goals, goals drive behavior"},
    "miner_013": {"expert": "Miner", "voice": "Accountability System", "focus": "Performance tracking", "principle": "Track metrics, what's measured improves"},
    "miner_014": {"expert": "Miner", "voice": "Team Development", "focus": "Sales coaching", "principle": "Coach your team, good coaching multiplies results"},
    "miner_015": {"expert": "Miner", "voice": "Mindset Cultivation", "focus": "Belief maintenance", "principle": "Cultivate winning mindset, mindset is half battle"},
    "miner_016": {"expert": "Miner", "voice": "Competitive Spirit", "focus": "Win mentality", "principle": "Compete to win, winning is only option"},
    "miner_017": {"expert": "Miner", "voice": "Continuous Improvement", "focus": "Daily growth", "principle": "Improve daily, small gains compound"},

    # ANDY ELLIOTT (17 prompts)
    "elliott_001": {"expert": "Elliott", "voice": "Radical Honesty", "focus": "Truth speaking", "principle": "Be radically honest, honesty builds trust"},
    "elliott_002": {"expert": "Elliott", "voice": "Accountability First", "focus": "Self responsibility", "principle": "Own your results, accountability drives growth"},
    "elliott_003": {"expert": "Elliott", "voice": "Problem Ownership", "focus": "Solution mindset", "principle": "Own problems, ownership enables solutions"},
    "elliott_004": {"expert": "Elliott", "voice": "Ego Release", "focus": "Pride removal", "principle": "Release ego, ego blocks growth"},
    "elliott_005": {"expert": "Elliott", "voice": "Execution Focus", "focus": "Action over talk", "principle": "Execute ruthlessly, action beats planning"},
    "elliott_006": {"expert": "Elliott", "voice": "High Standards", "focus": "Excellence pursuit", "principle": "Maintain high standards, excellence is standard"},
    "elliott_007": {"expert": "Elliott", "voice": "Speed to Market", "focus": "Fast iteration", "principle": "Move fast, iterate quickly, speed wins"},
    "elliott_008": {"expert": "Elliott", "voice": "Feedback Seeking", "focus": "Growth through feedback", "principle": "Seek honest feedback, feedback enables growth"},
    "elliott_009": {"expert": "Elliott", "voice": "Vulnerability Strength", "focus": "Authentic leadership", "principle": "Be vulnerable, vulnerability builds connection"},
    "elliott_010": {"expert": "Elliott", "voice": "Team Empowerment", "focus": "Delegate authority", "principle": "Empower teams, empowered teams execute"},
    "elliott_011": {"expert": "Elliott", "voice": "Values Alignment", "focus": "Principle consistency", "principle": "Live your values, consistency builds credibility"},
    "elliott_012": {"expert": "Elliott", "voice": "Growth Mindset", "focus": "Ability belief", "principle": "Believe in growth, growth mindset enables success"},
    "elliott_013": {"expert": "Elliott", "voice": "Challenge Seeking", "focus": "Stretch goals", "principle": "Seek challenges, challenges build strength"},
    "elliott_014": {"expert": "Elliott", "voice": "Pattern Recognition", "focus": "See the meta", "principle": "See patterns, patterns guide strategy"},
    "elliott_015": {"expert": "Elliott", "voice": "Consistency Practice", "focus": "Daily discipline", "principle": "Be consistent, consistency compounds"},
    "elliott_016": {"expert": "Elliott", "voice": "Simplicity", "focus": "Clarity focus", "principle": "Keep it simple, complexity masks truth"},
    "elliott_017": {"expert": "Elliott", "voice": "Service Philosophy", "focus": "Help mindset", "principle": "Serve others, service creates success"},

    # JONATAN LOIDI (17 prompts)
    "loidi_001": {"expert": "Loidi", "voice": "Digital Transformation", "focus": "Tech integration", "principle": "Embrace digital, technology multiplies output"},
    "loidi_002": {"expert": "Loidi", "voice": "Automation Obsession", "focus": "System scaling", "principle": "Automate everything, automation is freedom"},
    "loidi_003": {"expert": "Loidi", "voice": "Process Optimization", "focus": "Efficiency mastery", "principle": "Optimize processes, small efficiencies scale"},
    "loidi_004": {"expert": "Loidi", "voice": "Data-Driven Decisions", "focus": "Metrics focus", "principle": "Use data, data beats intuition"},
    "loidi_005": {"expert": "Loidi", "voice": "Lean Methodology", "focus": "Waste elimination", "principle": "Eliminate waste, lean is powerful"},
    "loidi_006": {"expert": "Loidi", "voice": "Agile Operations", "focus": "Flexibility", "principle": "Be agile, adapt quickly to changes"},
    "loidi_007": {"expert": "Loidi", "voice": "Growth Hacking", "focus": "Viral expansion", "principle": "Find growth levers, leverage creates exponential growth"},
    "loidi_008": {"expert": "Loidi", "voice": "Customer Data Insight", "focus": "Behavioral analytics", "principle": "Use customer data, data drives personalization"},
    "loidi_009": {"expert": "Loidi", "voice": "Conversion Optimization", "focus": "Funnel improvement", "principle": "Optimize conversions, small improvements multiply"},
    "loidi_010": {"expert": "Loidi", "voice": "Email Mastery", "focus": "Email revenue", "principle": "Master email, email is high ROI channel"},
    "loidi_011": {"expert": "Loidi", "voice": "Segmentation Strategy", "focus": "Targeted messaging", "principle": "Segment audiences, targeting increases relevance"},
    "loidi_012": {"expert": "Loidi", "voice": "Attribution Tracking", "focus": "Touchpoint measurement", "principle": "Track attribution, know what converts"},
    "loidi_013": {"expert": "Loidi", "voice": "Real-time Response", "focus": "Immediate action", "principle": "Respond in real-time, speed advantage"},
    "loidi_014": {"expert": "Loidi", "voice": "Testing Culture", "focus": "Experimentation", "principle": "Test everything, experimentation is discovery"},
    "loidi_015": {"expert": "Loidi", "voice": "Scalability Design", "focus": "System building", "principle": "Build scalable systems, systems scale beyond you"},
    "loidi_016": {"expert": "Loidi", "voice": "Technology Stack", "focus": "Tool selection", "principle": "Choose right tools, tools enable speed"},
    "loidi_017": {"expert": "Loidi", "voice": "Integration Excellence", "focus": "System harmony", "principle": "Integrate systems, integration is multiplier"},

    # LAURA RIBAS (17 prompts)
    "ribas_001": {"expert": "Ribas", "voice": "Marketing Psychology", "focus": "Behavioral economics", "principle": "Understand psychology, psychology drives behavior"},
    "ribas_002": {"expert": "Ribas", "voice": "Content Dominance", "focus": "Content authority", "principle": "Dominate content, content is currency"},
    "ribas_003": {"expert": "Ribas", "voice": "Brand Strategy", "focus": "Brand building", "principle": "Build strong brands, brands command premium"},
    "ribas_004": {"expert": "Ribas", "voice": "Customer Journey Mapping", "focus": "Touchpoint design", "principle": "Map journeys, touchpoints create conversion"},
    "ribas_005": {"expert": "Ribas", "voice": "Emotional Connection", "focus": "Heart engagement", "principle": "Connect emotionally, emotions drive decisions"},
    "ribas_006": {"expert": "Ribas", "voice": "Storytelling Commerce", "focus": "Narrative selling", "principle": "Use stories, stories sell powerfully"},
    "ribas_007": {"expert": "Ribas", "voice": "Visual Branding", "focus": "Design impact", "principle": "Design beautifully, beauty captures attention"},
    "ribas_008": {"expert": "Ribas", "voice": "Influencer Strategy", "focus": "Partnership leverage", "principle": "Leverage influencers, influence multiplies reach"},
    "ribas_009": {"expert": "Ribas", "voice": "Social Commerce", "focus": "Platform selling", "principle": "Sell on social, social removes friction"},
    "ribas_010": {"expert": "Ribas", "voice": "Community Engagement", "focus": "Audience building", "principle": "Build community, community is loyal"},
    "ribas_011": {"expert": "Ribas", "voice": "Trend Surfing", "focus": "Wave riding", "principle": "Catch trends early, timing is everything"},
    "ribas_012": {"expert": "Ribas", "voice": "Authenticity Marketing", "focus": "Real connection", "principle": "Be authentic, authenticity resonates"},
    "ribas_013": {"expert": "Ribas", "voice": "Voice Development", "focus": "Brand voice", "principle": "Develop unique voice, voice differentiates"},
    "ribas_014": {"expert": "Ribas", "voice": "Partnership Magic", "focus": "Collaboration power", "principle": "Collaborate strategically, partnerships amplify"},
    "ribas_015": {"expert": "Ribas", "voice": "Launch Strategy", "focus": "Market entry", "principle": "Plan launches carefully, momentum matters"},
    "ribas_016": {"expert": "Ribas", "voice": "Crisis Management", "focus": "Reputation protection", "principle": "Handle crises gracefully, reputation is fragile"},
    "ribas_017": {"expert": "Ribas", "voice": "Growth Through Sharing", "focus": "Value abundance", "principle": "Share generously, generosity creates abundance"},

    # MARCOS GALPERIN (16 prompts)
    "galperin_001": {"expert": "Galperin", "voice": "Market Timing", "focus": "Entry timing", "principle": "Timing is everything, right time beats right product"},
    "galperin_002": {"expert": "Galperin", "voice": "Platform Building", "focus": "Ecosystem creation", "principle": "Build platforms, platforms create network effects"},
    "galperin_003": {"expert": "Galperin", "voice": "Seller Empowerment", "focus": "Merchant success", "principle": "Empower sellers, seller success drives platform"},
    "galperin_004": {"expert": "Galperin", "voice": "Trust Building", "focus": "Safety systems", "principle": "Build trust systems, trust enables transactions"},
    "galperin_005": {"expert": "Galperin", "voice": "Payment Innovation", "focus": "Financial friction", "principle": "Reduce payment friction, ease drives adoption"},
    "galperin_006": {"expert": "Galperin", "voice": "Logistics Mastery", "focus": "Delivery excellence", "principle": "Master logistics, delivery defines experience"},
    "galperin_007": {"expert": "Galperin", "voice": "Global Expansion", "focus": "Market entry", "principle": "Expand globally, scale beyond borders"},
    "galperin_008": {"expert": "Galperin", "voice": "Competition Response", "focus": "Market defense", "principle": "Respond to competition quickly, speed matters"},
    "galperin_009": {"expert": "Galperin", "voice": "User Experience", "focus": "Frictionless design", "principle": "Design frictionless experience, UX drives adoption"},
    "galperin_010": {"expert": "Galperin", "voice": "Mobile First", "focus": "Mobile strategy", "principle": "Build for mobile, mobile is future"},
    "galperin_011": {"expert": "Galperin", "voice": "Data Leverage", "focus": "Information advantage", "principle": "Leverage data, data is competitive advantage"},
    "galperin_012": {"expert": "Galperin", "voice": "Category Creation", "focus": "Market definition", "principle": "Create categories, category leaders win"},
    "galperin_013": {"expert": "Galperin", "voice": "Community Building", "focus": "Seller community", "principle": "Build community around sellers, community sticks"},
    "galperin_014": {"expert": "Galperin", "voice": "Innovation Pace", "focus": "Feature velocity", "principle": "Innovate constantly, innovation keeps edge"},
    "galperin_015": {"expert": "Galperin", "voice": "Retention Focus", "focus": "Customer lock-in", "principle": "Retain users, retention is profitability"},
    "galperin_016": {"expert": "Galperin", "voice": "Ecosystem Investment", "focus": "Platform investment", "principle": "Invest in ecosystem, ecosystem creates value"},

    # PAOLO ROCCA (16 prompts)
    "rocca_001": {"expert": "Rocca", "voice": "Strategic Vision", "focus": "Long-term plan", "principle": "Vision guides decisions, long-term planning wins"},
    "rocca_002": {"expert": "Rocca", "voice": "Operational Excellence", "focus": "Execution mastery", "principle": "Execute excellently, operations win races"},
    "rocca_003": {"expert": "Rocca", "voice": "Technology Investment", "focus": "Innovation capital", "principle": "Invest in technology, technology is future"},
    "rocca_004": {"expert": "Rocca", "voice": "Supply Chain Mastery", "focus": "Production efficiency", "principle": "Master supply chain, efficiency is profit"},
    "rocca_005": {"expert": "Rocca", "voice": "Cost Leadership", "focus": "Lowest cost", "principle": "Be lowest cost, cost leadership is defensible"},
    "rocca_006": {"expert": "Rocca", "voice": "Quality Obsession", "focus": "Zero defects", "principle": "Obsess quality, quality is non-negotiable"},
    "rocca_007": {"expert": "Rocca", "voice": "Innovation Strategy", "focus": "Product development", "principle": "Innovate strategically, innovation drives growth"},
    "rocca_008": {"expert": "Rocca", "voice": "Team Building", "focus": "Talent development", "principle": "Build great teams, teams execute vision"},
    "rocca_009": {"expert": "Rocca", "voice": "Market Positioning", "focus": "Competitive position", "principle": "Position strategically, position drives success"},
    "rocca_010": {"expert": "Rocca", "voice": "Global Operations", "focus": "International scale", "principle": "Operate globally, scale across borders"},
    "rocca_011": {"expert": "Rocca", "voice": "Efficiency Culture", "focus": "Lean thinking", "principle": "Build efficiency culture, efficiency compounds"},
    "rocca_012": {"expert": "Rocca", "voice": "Risk Management", "focus": "Protect assets", "principle": "Manage risks prudently, protect downside"},
    "rocca_013": {"expert": "Rocca", "voice": "Stakeholder Value", "focus": "Multiple interests", "principle": "Create value for all stakeholders"},
    "rocca_014": {"expert": "Rocca", "voice": "Adaptation Ability", "focus": "Market response", "principle": "Adapt quickly, flexibility wins"},
    "rocca_015": {"expert": "Rocca", "voice": "Investment Discipline", "focus": "Capital allocation", "principle": "Discipline investments, discipline creates returns"},
    "rocca_016": {"expert": "Rocca", "voice": "Legacy Building", "focus": "Lasting impact", "principle": "Build lasting legacy, legacy is immortality"},

    # MIGUEL GALUCCIO + NAVAL RAVIKANT + NASSIM TALEB + PAUL GRAHAM + MARC BENIOFF (56 prompts remaining for 350 total)
    # Condensed for token efficiency
    "galuccio_001": {"expert": "Galuccio", "voice": "Energy Vision", "focus": "Sector leadership", "principle": "Vision attracts capital, vision drives industry"},
    "galuccio_002": {"expert": "Galuccio", "voice": "Sustainable Growth", "focus": "Responsible scale", "principle": "Grow responsibly, sustainability is strategy"},
    "galuccio_003": {"expert": "Galuccio", "voice": "Relationship Capital", "focus": "Stakeholder trust", "principle": "Build trust with all parties, trust enables deals"},

    "naval_001": {"expert": "Naval", "voice": "Building Leverage", "focus": "Scaling output", "principle": "Seek leverage, leverage multiplies output"},
    "naval_002": {"expert": "Naval", "voice": "Specific Knowledge", "focus": "Unique expertise", "principle": "Build specific knowledge, knowledge is wealth"},
    "naval_003": {"expert": "Naval", "voice": "Accountability", "focus": "Skin in game", "principle": "Have skin in game, accountability drives excellence"},
    "naval_004": {"expert": "Naval", "voice": "Compound Interest", "focus": "Time multiplication", "principle": "Let time compound, patience is wealth builder"},
    "naval_005": {"expert": "Naval", "voice": "Wealth vs Status", "focus": "Real vs fake", "principle": "Seek wealth not status, wealth is real power"},
    "naval_006": {"expert": "Naval", "voice": "Reading Mastery", "focus": "Knowledge acquisition", "principle": "Read everything, reading builds knowledge"},

    "taleb_001": {"expert": "Taleb", "voice": "Antifragility", "focus": "Thrive from chaos", "principle": "Build antifragile systems, chaos creates opportunity"},
    "taleb_002": {"expert": "Taleb", "voice": "Black Swan Thinking", "focus": "Tail risk", "principle": "Prepare for black swans, tail risks define outcomes"},
    "taleb_003": {"expert": "Taleb", "voice": "Optionality", "focus": "Keep options open", "principle": "Keep options, options are wealth"},
    "taleb_004": {"expert": "Taleb", "voice": "Skin in Game", "focus": "Real accountability", "principle": "Have skin in game, game drives honesty"},
    "taleb_005": {"expert": "Taleb", "voice": "Convexity", "focus": "Asymmetric upside", "principle": "Seek convexity, upside beats downside"},

    "graham_001": {"expert": "Graham", "voice": "Startup DNA", "focus": "Founder focus", "principle": "Back founders, founders build greatness"},
    "graham_002": {"expert": "Graham", "voice": "Product Market Fit", "focus": "Customer obsession", "principle": "Chase product-market fit, fit is everything"},
    "graham_003": {"expert": "Graham", "voice": "Rapid Iteration", "focus": "Learn fast", "principle": "Iterate rapidly, speed wins in startups"},
    "graham_004": {"expert": "Graham", "voice": "Startup Velocity", "focus": "Execution pace", "principle": "Move fast, velocity creates advantage"},
    "graham_005": {"expert": "Graham", "voice": "Investor Alignment", "focus": "Capital partnership", "principle": "Partner with aligned investors, alignment matters"},

    "benioff_001": {"expert": "Benioff", "voice": "Cloud Revolution", "focus": "Technology shift", "principle": "Ride cloud wave, technology creates wealth"},
    "benioff_002": {"expert": "Benioff", "voice": "Customer Success", "focus": "Client obsession", "principle": "Obsess customer success, success drives retention"},
    "benioff_003": {"expert": "Benioff", "voice": "Stakeholder Capitalism", "focus": "Multiple value", "principle": "Create value for all, stakeholders matter"},
    "benioff_004": {"expert": "Benioff", "voice": "Social Responsibility", "focus": "Greater good", "principle": "Do good with wealth, wealth creates responsibility"},
    "benioff_005": {"expert": "Benioff", "voice": "Innovation Culture", "focus": "Continuous learning", "principle": "Build innovation culture, culture drives future"},
}

def load_expert_prompts() -> dict:
    """Load 350 expert voices prompts into SellIA brain."""
    return EXPERT_PROMPTS
