"""ML Engine — Production-ready machine learning for SellIA."""

from ml_engine import (
    SupervisedLearner,
    UnsupervisedLearner,
    ReinforcementLearner,
    FeatureEngineer,
    ModelEvaluator,
)
from market_analysis_engine import (
    CompetitiveIntelligence,
    MarketTrendsAnalyzer,
    OwnAnalyzer,
    SWOTAnalyzer,
    ForecastingEngine,
)
from financial_analysis import (
    BudgetPlanner,
    CostAnalyzer,
    ProfitMarginCalculator,
    AssetsLiabilitiesTracker,
    CashFlowProjector,
    SensitivityAnalyzer,
)
from neural_networks import (
    # Base
    NeuralNetworkBase,
    ActivationFunction,
    NetworkConfig,
    TrainingConfig,
    # Prediction
    SalesPredictionNetwork,
    ChurnPredictionNetwork,
    DemandForecastingNetwork,
    LeadQualityNetwork,
    ContactTimingNetwork,
    PriceElasticityNetwork,
    # Optimization
    PricingOptimizationNetwork,
    ChannelOptimizationNetwork,
    MessageTimingNetwork,
    BudgetAllocationNetwork,
    FeatureImportanceNetwork,
    # Pattern Recognition
    MarketPatternRecognizer,
    CustomerBehaviorRecognizer,
    CompetitorPatternRecognizer,
    CommunicationPatternRecognizer,
    AnomalyDetector,
    # Recommendations
    StrategyRecommender,
    SalesMethodRecommender,
    PricingRecommender,
    ChannelRecommender,
    MessageToneRecommender,
    # Learning
    OnlineLearningEngine,
    TransferLearningEngine,
    MetaLearningEngine,
    FewShotLearner,
    ActiveLearner,
    # Attention
    FeatureAttention,
    TemporalAttention,
    SpatialAttention,
    CrossModalAttention,
    # Ensemble
    EnsemblePredictor,
    UncertaintyEstimator,
    ModelSelector,
    BoostingEngine,
    BaggingEngine,
)

__all__ = [
    # Original ML modules
    "SupervisedLearner",
    "UnsupervisedLearner",
    "ReinforcementLearner",
    "FeatureEngineer",
    "ModelEvaluator",
    "CompetitiveIntelligence",
    "MarketTrendsAnalyzer",
    "OwnAnalyzer",
    "SWOTAnalyzer",
    "ForecastingEngine",
    "BudgetPlanner",
    "CostAnalyzer",
    "ProfitMarginCalculator",
    "AssetsLiabilitiesTracker",
    "CashFlowProjector",
    "SensitivityAnalyzer",
    # Neural Networks
    "NeuralNetworkBase",
    "ActivationFunction",
    "NetworkConfig",
    "TrainingConfig",
    "SalesPredictionNetwork",
    "ChurnPredictionNetwork",
    "DemandForecastingNetwork",
    "LeadQualityNetwork",
    "ContactTimingNetwork",
    "PriceElasticityNetwork",
    "PricingOptimizationNetwork",
    "ChannelOptimizationNetwork",
    "MessageTimingNetwork",
    "BudgetAllocationNetwork",
    "FeatureImportanceNetwork",
    "MarketPatternRecognizer",
    "CustomerBehaviorRecognizer",
    "CompetitorPatternRecognizer",
    "CommunicationPatternRecognizer",
    "AnomalyDetector",
    "StrategyRecommender",
    "SalesMethodRecommender",
    "PricingRecommender",
    "ChannelRecommender",
    "MessageToneRecommender",
    "OnlineLearningEngine",
    "TransferLearningEngine",
    "MetaLearningEngine",
    "FewShotLearner",
    "ActiveLearner",
    "FeatureAttention",
    "TemporalAttention",
    "SpatialAttention",
    "CrossModalAttention",
    "EnsemblePredictor",
    "UncertaintyEstimator",
    "ModelSelector",
    "BoostingEngine",
    "BaggingEngine",
]
