{{ if and .Values.clamav.enabled .Values.clamav.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sellia.fullname" . }}-clamav-data
  labels:
    {{- include "sellia.labels" . | nindent 4 }}
    app.kubernetes.io/component: clamav
spec:
  accessModes:
    - {{ .Values.clamav.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.clamav.persistence.size }}
{{ end }}
