{{ if .Values.networkPolicy.enabled }}
{{ range $name, $policy := .Values.networkPolicy }}
{{- if ne $name "enabled" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sellia.fullname" $ }}-{{ $name }}
  labels:
    {{- include "sellia.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "sellia.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  policyTypes:
    - Ingress
  ingress:
    {{- toYaml $policy.ingress | nindent 4 }}
---
{{- end }}
{{- end }}
{{ end }}
