apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sellia.fullname" . }}-secrets
  labels:
    {{- include "sellia.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ required "secretKey is required" .Values.secrets.secretKey | quote }}
  database-url: {{ required "databaseUrl is required" .Values.secrets.databaseUrl | quote }}
  redis-url: {{ required "redisUrl is required" .Values.secrets.redisUrl | quote }}
  turnstile-secret-key: {{ .Values.secrets.turnstileSecretKey | default "" | quote }}
  vapid-private-key: {{ .Values.secrets.vapidPrivateKey | default "" | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | default "" | quote }}
  hibp-api-key: {{ .Values.secrets.hibpApiKey | default "" | quote }}
  elk-api-key: {{ .Values.secrets.elkApiKey | default "" | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | default "" | quote }}
  database-password: {{ .Values.secrets.databasePassword | default "" | quote }}
  redis-password: {{ .Values.secrets.redisPassword | default "" | quote }}
