"""Instagram automation models: @sell_.ia brand promotion."""
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, Text, JSON
from app.db.database import Base


class InstagramPost(Base):
    """Instagram content generated by FeedIA + SellIA synergy."""
    __tablename__ = "instagram_posts"

    id = Column(String(36), primary_key=True)
    caption = Column(Text)  # Post caption
    hashtags = Column(String(500))  # Hashtags: #sell_.ia #AI #SalesTech
    content_type = Column(String(50))  # carousel, reel, story, static
    media_url = Column(String(500))  # Image/video URL
    posted_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    scheduled_for = Column(DateTime(timezone=True), nullable=True)

    # Publish status real (no simulado)
    publish_status = Column(String(30), default="draft")  # draft, pending_credentials, published, failed
    fomo_application_id = Column(String(36), nullable=True)  # FK a fomo_strategy_applications
    ig_media_id = Column(String(100), nullable=True)  # ID real devuelto por Graph API
    ig_permalink = Column(String(500), nullable=True)  # URL real del post publicado
    publish_error = Column(Text, nullable=True)  # Error crudo de Graph API si falló

    # Performance
    likes = Column(Integer, default=0)
    comments = Column(Integer, default=0)
    shares = Column(Integer, default=0)
    saves = Column(Integer, default=0)
    engagement_rate = Column(Float, default=0.0)

    # Links back to SellIA
    cta_link = Column(String(500))  # Link to landing page
    utm_params = Column(String(200))  # utm_source=instagram utm_medium=post
    conversions_attributed = Column(Integer, default=0)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class InstagramCampaign(Base):
    """Multi-post Instagram campaign coordinated by SellIA + FeedIA."""
    __tablename__ = "instagram_campaigns"

    id = Column(String(36), primary_key=True)
    name = Column(String(255))  # "Q3 2026 SellIA Launch" etc
    theme = Column(String(100))  # "social_proof" "founder_story" "feature_highlight"
    target_audience = Column(String(100))  # "B2B_founders" "sales_leaders" "marketers"

    # Content strategy
    num_posts_planned = Column(Integer)  # 7, 14, 30 day campaigns
    post_frequency = Column(String(50))  # daily, 3x_weekly, twice_daily
    content_mix = Column(JSON)  # {reels: 0.4, carousels: 0.3, stories: 0.3}

    # Performance
    total_impressions = Column(Integer, default=0)
    total_engagement = Column(Integer, default=0)
    avg_engagement_rate = Column(Float, default=0.0)
    conversions = Column(Integer, default=0)
    roi = Column(Float, default=0.0)  # (conversions * avg_deal_value) / cost

    # Synergy
    feedia_integration = Column(Boolean, default=True)  # Uses FeedIA content generation
    sellbox_link = Column(String(500))  # Direct link to SellIA

    status = Column(String(50), default="draft")  # draft, scheduled, active, completed
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    launched_at = Column(DateTime(timezone=True), nullable=True)
    ended_at = Column(DateTime(timezone=True), nullable=True)


class InstagramAudience(Base):
    """Audience segments following @sell_.ia + content preferences."""
    __tablename__ = "instagram_audiences"

    id = Column(String(36), primary_key=True)
    handle = Column(String(100))  # @username or email for tracking
    follower_count = Column(Integer, default=0)
    engagement_rate = Column(Float, default=0.0)

    # Profile
    industry = Column(String(100))
    job_title = Column(String(100))
    company_size = Column(String(50))

    # Interest signals
    follows_competitors = Column(Boolean, default=False)
    engages_with_content = Column(Boolean, default=False)
    has_clicked_cta = Column(Boolean, default=False)
    has_visited_landing_page = Column(Boolean, default=False)

    # Sales funnel
    is_leadmagnet_subscriber = Column(Boolean, default=False)
    is_trial_user = Column(Boolean, default=False)
    is_customer = Column(Boolean, default=False)

    first_interaction_at = Column(DateTime(timezone=True), nullable=True)
    last_interaction_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class InstagramConversionPath(Base):
    """Attribution: Instagram interaction → Landing page → Lead → Customer."""
    __tablename__ = "instagram_conversion_paths"

    id = Column(String(36), primary_key=True)
    user_id = Column(String(36))

    # Path stages
    instagram_interaction_at = Column(DateTime(timezone=True))  # Like/comment/share/click
    instagram_post_id = Column(String(36))
    campaign_id = Column(String(36))

    landing_page_visit_at = Column(DateTime(timezone=True), nullable=True)
    utm_source = Column(String(100), default="instagram")
    utm_medium = Column(String(100))  # story, reel, carousel, comment
    utm_campaign = Column(String(100))

    lead_created_at = Column(DateTime(timezone=True), nullable=True)
    lead_magnet_downloaded = Column(String(50), nullable=True)  # ebook, calculator, etc

    trial_started_at = Column(DateTime(timezone=True), nullable=True)
    demo_scheduled_at = Column(DateTime(timezone=True), nullable=True)

    deal_closed_at = Column(DateTime(timezone=True), nullable=True)
    deal_value = Column(Float, nullable=True)

    # Metrics
    time_to_conversion = Column(Integer, nullable=True)  # days
    touches_before_conversion = Column(Integer, default=0)
    instagram_attribution_credit = Column(Float, default=0.0)  # 0-1.0

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
